---
- hosts: all
  tasks:
  - name: Get .vimrc
    get_url:
      url: https://raw.githubusercontent.com/ashildmy/Dotfiles/master/.vimrc
      dest: ~/.vimrc
      mode: 0644
      force: yes

  - name: Create Colors Folder with Correct Permissions
    file:
      path: ~/.vim/colors
      state: directory
      mode: 0755

  - name: Get Vim Colors
    get_url:
      url: https://raw.githubusercontent.com/chriskempson/vim-tomorrow-theme/master/colors/Tomorrow-Night-Eighties.vim
      dest: ~/.vim/colors/tomorrow-night-eighties.vim
      mode: 0644

  - name: Get tmux.conf
    get_url:
      url: https://raw.githubusercontent.com/ashildmy/Dotfiles/master/tmux.conf
      dest: ~/.tmux.conf
      force: yes

- hosts: centos
  tasks:
  - name: Install Git
    yum:
      name: git
      state: latest

  - name: Install Vim
    yum:
      name: vim
      state: latest

  - name: Clone Vundle
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim 

  - name: Install Vundle
    command: vim +PluginInstall +qall

  - name: Install Tmux
    yum:
      name: tmux
      state: latest

  become: yes
  become_method: sudo

- hosts: ubuntu
  tasks:
  - name: Update all packages
    apt:
      upgrade: dist

  - name: Install Git
    apt:
      name: git
      state: latest

# This will install to root directory since the "become" method has escalated to user root
# TODO: Fix where this is installed.  Look into installing for specific users.
  - name: Clone Vundle
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim 

  - name: Install Vim
    apt:
      name: vim
      state: latest

  - name: Install Vundle
    command: vim +PluginInstall +qall

  - name: Install Tmux
    apt:
      name: tmux
      state: latest

  become: yes
  become_method: sudo

